version: '1'
services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - server
  server:
    build:
      context: './server'
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'